### ISSUE TITLE
Great initiative and may need public forums?

### ISSUE THREAD

**Issue by rajasegar** [CodeshiftCommunity/CodeshiftCommunity#20]
Thanks a lot for creating this community, it is a great start to spread awareness about codemods and automated migration tools. 
Being a codemod author brings joy to see these kind of initiatives from the community. Does it make sense to have a forum in Slack or Discord for the community to get help, discuss and build codemods or is it too early?

I leave the timelines to you folks since you are the best people to make the decisions. Thanks once again and would be glad to help in anyway possible.

**Comment by danieldelcore** [comment]
Thanks a lot for the kind words! Really gratifying to hear that after working on this project for so long haha! 

Yeah I would love to setup some sort of Slack/Discord/etc. No worries about timing, I think having it there before launch is a good idea so people can jump right in and ask questions / self-serve! 

Also, you're more than welcome to jump in and contribute if you have an idea or see something that needs attention! Would especially appreciate someone with a solid understanding of the current codemod ecosystem helping out too 😉!

**Comment by danieldelcore** [comment]
Actually come to think of it! I would LOVE to turn on GitHub Discussions to keep everything centralised. I'll have to see if it's possible for us

**Comment by danieldelcore** [comment]
Done! 

https://github.com/CodeshiftCommunity/CodeshiftCommunity/discussions

Let's go with this! Will close this issue for now but please lmk if you'd like to discuss further! 🚀🚀
