### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by danieldelcore** [CodeshiftCommunity/CodeshiftCommunity#3]
Take some inspo from the CRA home page. 

https://create-react-app.dev/
http://testing-library.com/

![image](https://user-images.githubusercontent.com/3030010/116488704-5eb01d80-a8d6-11eb-88ae-3d37ec5e9dc8.png)

**Comment by danielo515** [comment]
I think the home-page is already very good

**Comment by danieldelcore** [comment]
Done #72
