### ISSUE TITLE
"Preset" codemods that aren't tied to a specific module or version.

### ISSUE THREAD

**Issue by danieldelcore** [CodeshiftCommunity/CodeshiftCommunity#4]
Think of things like "Skip a test" or "Remove white space".

**Comment by rajasegar** [comment]
Skip a test sounds like a good idea. But Remove white space is already done by eslint and prettier, do we really need them?

**Comment by danieldelcore** [comment]
Hey @rajasegar! Hahah probably not, these are just examples from the top of my head! 

I'm thinking this will realistically be codemods that are generic in that they can be applied to any code base and organised into thematic groups like for example "imports" might have "sort imports", "require-to-import" something like that. But that's not to say I'm going to build them, but more so that I want to provide a way for these codemods to be publishable with this project 😄. 
Hope that makes sense! Thanks for showing interest!

**Comment by danieldelcore** [comment]
This functionality is available in 0.2.1
