### ISSUE TITLE
misc: link from Authoring to Contribution guide is broken

### ISSUE THREAD

**Issue by kiprasmel** [CodeshiftCommunity/CodeshiftCommunity#55]
from:
- https://www.codeshiftcommunity.com/docs/authoring

links to:
- https://www.codeshiftcommunity.com/docs/authoring/docs/contribution

when should link to:
- https://www.codeshiftcommunity.com/docs/contribution

tried fixing it but haven't used mdx before so dunno how, it didn't work, so just fyi.

**Comment by danieldelcore** [comment]
Done!
