### ISSUE TITLE
Generic codemods

### ISSUE THREAD

**Issue by danieldelcore** [CodeshiftCommunity/CodeshiftCommunity#8]
There are a lot of codemods that are written for general use. 
Consider "sort imports", "convert to arrow function" etc

These should have a home in this repo too for people who might find them useful.

My suggestion is to provide a `preset` folder which behaves similarly to the `community` folder, but without the restrictions on file names etc.

**Comment by rajasegar** [comment]
I already maintain an awesome list here, please feel free to pick anything from there
https://github.com/rajasegar/awesome-codemods

**Comment by danieldelcore** [comment]
Amazing will do, thanks for sharing!

**Comment by danieldelcore** [comment]
This features is now available via: https://github.com/CodeshiftCommunity/CodeshiftCommunity/pull/46
