### ISSUE TITLE
Add ast-builder to resources Ecosystem / Tools

### ISSUE THREAD

**Issue by mbrookes** [CodeshiftCommunity/CodeshiftCommunity#9]
https://rajasegar.github.io/ast-builder/

**Comment by danieldelcore** [comment]
ooh would love to! Thanks for sharing!

**Comment by danieldelcore** [comment]
Done! Feel free to raise a PR if you spot anything that's missing 😄 

Should be up shortly 👍 
https://www.codeshiftcommunity.com/docs/ecosystem
